// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3I303JrKmQdrkRQDRV2EgbWBkftzxN8s',
    appId: '1:1087601252610:web:fafeea4e1e0f3b9c004a1b',
    messagingSenderId: '1087601252610',
    projectId: 'loginpage-e4e68',
    authDomain: 'loginpage-e4e68.firebaseapp.com',
    storageBucket: 'loginpage-e4e68.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpuMRdl24SWPap1-izN7WRAsVd156a7TU',
    appId: '1:1087601252610:android:168f91a09ee1e657004a1b',
    messagingSenderId: '1087601252610',
    projectId: 'loginpage-e4e68',
    storageBucket: 'loginpage-e4e68.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiKgLySpUzgtyIuim0FaS6N4CXXjlFov4',
    appId: '1:1087601252610:ios:032eb407d557069a004a1b',
    messagingSenderId: '1087601252610',
    projectId: 'loginpage-e4e68',
    storageBucket: 'loginpage-e4e68.appspot.com',
    iosClientId: '1087601252610-4n5p390jlq2ma2b1g84qnh4fka28v9uo.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginpage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiKgLySpUzgtyIuim0FaS6N4CXXjlFov4',
    appId: '1:1087601252610:ios:032eb407d557069a004a1b',
    messagingSenderId: '1087601252610',
    projectId: 'loginpage-e4e68',
    storageBucket: 'loginpage-e4e68.appspot.com',
    iosClientId: '1087601252610-4n5p390jlq2ma2b1g84qnh4fka28v9uo.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginpage',
  );
}
